# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cirocket < Formula
  desc "Rocket powered task runner to assist delivering ci build missions"
  homepage "https://github.com/nehemming/cirocket"
  version "0.3.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nehemming/cirocket/releases/download/v0.3.0/cirocket_0.3.0_Darwin_x86_64.tar.gz"
      sha256 "3c74ad6168985e0654f9af174d8b624769d4237da95817fa0a96557e3addb383"
    end
    if Hardware::CPU.arm?
      url "https://github.com/nehemming/cirocket/releases/download/v0.3.0/cirocket_0.3.0_Darwin_arm64.tar.gz"
      sha256 "2638c0aef427650a105574d6cb9678b616b6c52eb523dc62cadd73920408b5e1"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/nehemming/cirocket/releases/download/v0.3.0/cirocket_0.3.0_Linux_x86_64.tar.gz"
      sha256 "1820357eb3759dfff2fd1ebfa6ec4229bbce0bf0e091bfd0112522b4acf362b5"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nehemming/cirocket/releases/download/v0.3.0/cirocket_0.3.0_Linux_arm64.tar.gz"
      sha256 "78531fbafe40c022335c7592450f779f1ac97e4cb66850e984e64db087e01068"
    end
  end

  def install
    bin.install "cirocket"
  end
end
