# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cirocket < Formula
  desc "Rocket powered task runner to assist delivering ci build missions"
  homepage "https://github.com/nehemming/cirocket"
  version "0.2.1"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nehemming/cirocket/releases/download/v0.2.1/cirocket_0.2.1_Darwin_x86_64.tar.gz"
      sha256 "e4a3dcf0e4f1b52ca77664beba0e7e22623e5067aedc4032e3744af58ebf57f3"
    end
    if Hardware::CPU.arm?
      url "https://github.com/nehemming/cirocket/releases/download/v0.2.1/cirocket_0.2.1_Darwin_arm64.tar.gz"
      sha256 "01a849c9115c9fef1ababd78d61f6867216a1f28017e2dd1f0cec245ac8a6977"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/nehemming/cirocket/releases/download/v0.2.1/cirocket_0.2.1_Linux_x86_64.tar.gz"
      sha256 "6b943ba47e47a7251f12812548908e2bac19700725136daf4766850feec62646"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nehemming/cirocket/releases/download/v0.2.1/cirocket_0.2.1_Linux_arm64.tar.gz"
      sha256 "656521ca04c72c5ac04da8e6ac2697562626155d2d92944cb7b1ad924860f1b4"
    end
  end

  def install
    bin.install "cirocket"
  end
end
