# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cirocket < Formula
  desc "Rocket powered task runner to assist delivering ci build missions"
  homepage "https://github.com/nehemming/cirocket"
  version "0.1.2"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nehemming/cirocket/releases/download/v0.1.2/cirocket_0.1.2_Darwin_x86_64.tar.gz"
      sha256 "9619f9d34e17d13843c5de199c3747922dfb68bd2a8cece357e88e8237ede125"
    end
    if Hardware::CPU.arm?
      url "https://github.com/nehemming/cirocket/releases/download/v0.1.2/cirocket_0.1.2_Darwin_arm64.tar.gz"
      sha256 "ca7ddd0f8f28e37b48359358f7124e1a308e4403e19a957743731d06ddcd5324"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/nehemming/cirocket/releases/download/v0.1.2/cirocket_0.1.2_Linux_x86_64.tar.gz"
      sha256 "9a189ee958298b5d940063643209fe061947a061b58432c72a18b84a3a5fb1cf"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nehemming/cirocket/releases/download/v0.1.2/cirocket_0.1.2_Linux_arm64.tar.gz"
      sha256 "0dbc9a5d98de2ade9313fe54ad6b4d9cdd23183085046947cf1cd80b0f7186da"
    end
  end

  def install
    bin.install "cirocket"
  end
end
