# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oauthproxy < Formula
  desc "A oauth2 proxy token caching service for password authentication flows."
  homepage "https://github.com/nehemming/oauthproxy"
  version "0.0.2"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nehemming/oauthproxy/releases/download/v0.0.2/oauthproxy_0.0.2_Darwin_x86_64.tar.gz"
      sha256 "ece6e260c411f37cbbb3ac2dbcf975bfdc6a63008a61e351332cc1c0009ecc0a"
    end
    if Hardware::CPU.arm?
      url "https://github.com/nehemming/oauthproxy/releases/download/v0.0.2/oauthproxy_0.0.2_Darwin_arm64.tar.gz"
      sha256 "29ff8a5bd686886494e6078eb2e7fb7ed7571dc7eaf5294418d00ab61885ca5c"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/nehemming/oauthproxy/releases/download/v0.0.2/oauthproxy_0.0.2_Linux_x86_64.tar.gz"
      sha256 "58cb4bc9ea35e615e727e5f3d12a1e36ce634802fff98a6d8648c02501685df7"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nehemming/oauthproxy/releases/download/v0.0.2/oauthproxy_0.0.2_Linux_arm64.tar.gz"
      sha256 "1ddeaa774e7cebf444f12d54cf2a7082f16f394c0957208cb8149c9968d3f015"
    end
  end

  def install
    bin.install "oauthproxy"
  end
end
